[package]
name = "todo_web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.9.0"
futures = "0.3.30"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
